// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: secrets.proto

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Secrets_GetUserSecretsV1_FullMethodName   = "/proto.keeper.grpcapi.Secrets/GetUserSecretsV1"
	Secrets_GetUserSecretV1_FullMethodName    = "/proto.keeper.grpcapi.Secrets/GetUserSecretV1"
	Secrets_SaveUserSecretV1_FullMethodName   = "/proto.keeper.grpcapi.Secrets/SaveUserSecretV1"
	Secrets_DeleteUserSecretV1_FullMethodName = "/proto.keeper.grpcapi.Secrets/DeleteUserSecretV1"
)

// SecretsClient is the client API for Secrets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecretsClient interface {
	GetUserSecretsV1(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetUserSecretsResponseV1, error)
	GetUserSecretV1(ctx context.Context, in *GetUserSecretRequestV1, opts ...grpc.CallOption) (*GetUserSecretResponseV1, error)
	SaveUserSecretV1(ctx context.Context, in *SaveUserSecretRequestV1, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteUserSecretV1(ctx context.Context, in *DeleteUserSecretRequestV1, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type secretsClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretsClient(cc grpc.ClientConnInterface) SecretsClient {
	return &secretsClient{cc}
}

func (c *secretsClient) GetUserSecretsV1(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetUserSecretsResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSecretsResponseV1)
	err := c.cc.Invoke(ctx, Secrets_GetUserSecretsV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsClient) GetUserSecretV1(ctx context.Context, in *GetUserSecretRequestV1, opts ...grpc.CallOption) (*GetUserSecretResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSecretResponseV1)
	err := c.cc.Invoke(ctx, Secrets_GetUserSecretV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsClient) SaveUserSecretV1(ctx context.Context, in *SaveUserSecretRequestV1, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Secrets_SaveUserSecretV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsClient) DeleteUserSecretV1(ctx context.Context, in *DeleteUserSecretRequestV1, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Secrets_DeleteUserSecretV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretsServer is the server API for Secrets service.
// All implementations must embed UnimplementedSecretsServer
// for forward compatibility.
type SecretsServer interface {
	GetUserSecretsV1(context.Context, *emptypb.Empty) (*GetUserSecretsResponseV1, error)
	GetUserSecretV1(context.Context, *GetUserSecretRequestV1) (*GetUserSecretResponseV1, error)
	SaveUserSecretV1(context.Context, *SaveUserSecretRequestV1) (*emptypb.Empty, error)
	DeleteUserSecretV1(context.Context, *DeleteUserSecretRequestV1) (*emptypb.Empty, error)
	mustEmbedUnimplementedSecretsServer()
}

// UnimplementedSecretsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretsServer struct{}

func (UnimplementedSecretsServer) GetUserSecretsV1(context.Context, *emptypb.Empty) (*GetUserSecretsResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSecretsV1 not implemented")
}
func (UnimplementedSecretsServer) GetUserSecretV1(context.Context, *GetUserSecretRequestV1) (*GetUserSecretResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSecretV1 not implemented")
}
func (UnimplementedSecretsServer) SaveUserSecretV1(context.Context, *SaveUserSecretRequestV1) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveUserSecretV1 not implemented")
}
func (UnimplementedSecretsServer) DeleteUserSecretV1(context.Context, *DeleteUserSecretRequestV1) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserSecretV1 not implemented")
}
func (UnimplementedSecretsServer) mustEmbedUnimplementedSecretsServer() {}
func (UnimplementedSecretsServer) testEmbeddedByValue()                 {}

// UnsafeSecretsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretsServer will
// result in compilation errors.
type UnsafeSecretsServer interface {
	mustEmbedUnimplementedSecretsServer()
}

func RegisterSecretsServer(s grpc.ServiceRegistrar, srv SecretsServer) {
	// If the following call pancis, it indicates UnimplementedSecretsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Secrets_ServiceDesc, srv)
}

func _Secrets_GetUserSecretsV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServer).GetUserSecretsV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Secrets_GetUserSecretsV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServer).GetUserSecretsV1(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Secrets_GetUserSecretV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSecretRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServer).GetUserSecretV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Secrets_GetUserSecretV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServer).GetUserSecretV1(ctx, req.(*GetUserSecretRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Secrets_SaveUserSecretV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUserSecretRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServer).SaveUserSecretV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Secrets_SaveUserSecretV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServer).SaveUserSecretV1(ctx, req.(*SaveUserSecretRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Secrets_DeleteUserSecretV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserSecretRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServer).DeleteUserSecretV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Secrets_DeleteUserSecretV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServer).DeleteUserSecretV1(ctx, req.(*DeleteUserSecretRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

// Secrets_ServiceDesc is the grpc.ServiceDesc for Secrets service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Secrets_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.keeper.grpcapi.Secrets",
	HandlerType: (*SecretsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserSecretsV1",
			Handler:    _Secrets_GetUserSecretsV1_Handler,
		},
		{
			MethodName: "GetUserSecretV1",
			Handler:    _Secrets_GetUserSecretV1_Handler,
		},
		{
			MethodName: "SaveUserSecretV1",
			Handler:    _Secrets_SaveUserSecretV1_Handler,
		},
		{
			MethodName: "DeleteUserSecretV1",
			Handler:    _Secrets_DeleteUserSecretV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secrets.proto",
}
